[package]
name = "learn-tower"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "1.4.0", features = ["full"] }
hyper-util = { version = "0.1.6", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
tower = "0.4.13"
warp = "0.3.7"
